spring:
   datasource:
      url: jdbc:mysql://localhost:3306/account
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.mchange.v2.c3p0.ComboPooledDataSource
   logging:
      level: trace
   thymeleaf:
      prefix: classpath:templates/
mybatis-plus:
   global-config:
      id-type: 0
shiro:
   enabled: true
